/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sdp.prac2;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

<<<<<<< HEAD
import java.util.List;

class AppTest {
    
    @Test void Task3Test(){
        SimpleFunctions classBeingTested = new SimpleFunctions();
        String test1 = "(hello)";
        String test2 = "()";

        boolean result1 = classBeingTested.Task3(test1);
        boolean result2 = classBeingTested.Task3(test2);

        assertEquals(true, test1);
        assertEquals(true,test2)


    }
=======
import java.util.*;

class AppTest {
    @Test void Task2Test() {
        // Arrange
        SimpleFunctions classBeingTested = new SimpleFunctions();

        List<String> test1 = Arrays.asList("John", "Tyler", "Etienne");
        List<String> test2 = Arrays.asList();
        List<String> test3 = Arrays.asList("middle", "", "is", "Empty");
        List<String> expected1 = Arrays.asList("ohn", "yler", "tienne");
        List<String> expected2 = Arrays.asList();
        List<String> expected3 = Arrays.asList("iddle", "s", "mpty");
        // Act
        List<String> result1 = classBeingTested.Task2(test1);
        List<String> result2 = classBeingTested.Task2(test2);
        List<String> result3 = classBeingTested.Task2(test3);
        // Assert
        assertIterableEquals(expected1, result1);
        assertIterableEquals(expected2, result2);
        assertIterableEquals(expected3, result3);
    }

>>>>>>> 8489eef4c7e5b30ba9410c2e41295a5ffe22aa96
}
